# Nixpacks configuration for Railway deployment
[phases.setup]
  nixPkgs = ['python311']

[phases.install]  
  cmds = ['pip install --no-cache-dir -r requirements.txt']

[start]
  cmd = 'python backend.py'
