services:
  - type: web
    name: lexi-guide-api
    env: python
    plan: free
    buildCommand: "./build.sh"
    startCommand: "python backend.py"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.7
      - key: PORT
        value: 10000
      - key: ENVIRONMENT
        value: production
    autoDeploy: true
    scaling:
      minInstances: 1
      maxInstances: 1